# Generated by Django 2.2.2 on 2019-07-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='img/beautiful-landscape.jpg', upload_to='portraits'),
        ),
    ]
