# Generated by Django 2.2.2 on 2019-07-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190704_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='img/beautiful-landscape.jpg', upload_to=''),
        ),
    ]
