# Generated by Django 2.2.2 on 2019-07-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190704_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='picture/beautiful-landscape.jpg', upload_to=''),
        ),
    ]
