# Generated by Django 2.2.2 on 2019-09-21 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190704_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
