# Generated by Django 2.2.2 on 2019-06-30 12:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='Image',
            field=models.ImageField(default='img/beautiful-landscape.jpg', upload_to='pictures/'),
        ),
    ]
