# Generated by Django 2.2.2 on 2019-07-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Rejected',
            field=models.BooleanField(default=False),
        ),
    ]
