# Generated by Django 2.2.2 on 2019-07-11 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190704_1339'),
        ('blogs', '0004_post_rejected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Author',
        ),
        migrations.AddField(
            model_name='post',
            name='Author',
            field=models.ManyToManyField(to='users.Profile'),
        ),
    ]
