# Generated by Django 2.2.2 on 2019-07-12 06:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_auto_20190711_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Description',
            field=ckeditor.fields.RichTextField(default='This is a sample description'),
        ),
    ]
