# Generated by Django 2.2.2 on 2019-07-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_auto_20190711_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Description',
            field=models.TextField(default='This is a sample Description'),
        ),
    ]
