# Generated by Django 2.2.2 on 2020-02-24 05:29

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_auto_20190713_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Content',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
