# Generated by Django 2.2.2 on 2020-03-08 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_auto_20200223_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Content',
            field=models.TextField(),
        ),
    ]
